# Cloudflare configuration for MD2HTML
# Enhanced by terriyaki for production deployment
# This file now references the new JavaScript-based API structure

# Note: This file is kept for reference. 
# The actual Worker configuration is in api/wrangler.toml
# Frontend deployment uses Cloudflare Pages build settings

name = "md2html-legacy"
compatibility_date = "2024-01-01"

# Legacy configuration - Flask version is preserved but not deployed
# New deployments should use:
# - api/wrangler.toml for Cloudflare Workers API
# - frontend/ directory for Cloudflare Pages frontend